all: html

SPHINX_PROJECT_NAME = Serial to Ethernet briding application Quickstart Guide
VERSION = 1.0
SOURCE_INCLUDE_DIRS = ../app_serial_to_ethernet
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
