SPHINX_PROJECT_NAME = Application to demonstrate Serial to Ethernet bridging
VERSION = 0.1
DOXYGEN_DIRS = ../app_serial_to_ethernet
SOURCE_INCLUDE_DIRS = ../sw_serial_to_ethernet/app_serial_to_ethernet
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
