SPHINX_PROJECT_NAME = Serial to Ethernet briding application quickstart guide
VERSION = 1.1
SOURCE_INCLUDE_DIRS = ../../app_serial_to_ethernet
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc

