SPHINX_PROJECT_NAME = Serial to Ethernet bridging application note
VERSION = 0.1
DOXYGEN_DIRS = ../app_serial_to_ethernet
SOURCE_INCLUDE_DIRS = ../app_serial_to_ethernet
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
